<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">mod10Service</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWZpbmFsSW4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgImZpbmFsSW4iICk7DQoJSW50ZWdlciBudW09SW50ZWdlci5wYXJzZUludChmaW5hbElu
KTsNCglTdHJpbmcgc3RhdHVzOw0KCWlmIChudW0gJSAxMCA9PSAwKSB7c3RhdHVzPSIqKioqKioq
KioqVmFsaWRhdGVkIENyZWRpdCBDYXJkIGlzIFZhbGlkIGFuZCBSZWFkeSB0byBVc2UqKioqKioq
KioqKioiO30NCgllbHNlIHsNCgkJc3RhdHVzPSIqKioqKioqKioqSW5BY3RpdmUgQ3JlZGl0IENh
cmQsIFBMZWFzZSBjaGVjayBmcm9tIGJhbmsgaWYgaXQgaGFzIGJlZW4gZGlzYWJsZWQgb3IgUGVy
bWFuZW50bHkgSW5BY3RpdmUqKioqKioqKioiOw0KICAgIH0NCgkNCnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTsNCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBw
aXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJz
dGF0dXMiLCBzdGF0dXMgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
