<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeToFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCWZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJmaWxlTmFtZSIgKTsNCglTdHJpbmcJaW5wdXRTdHIgPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImlucHV0U3RyIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOw0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOw0KDQpGaWxlIGY9bmV3IEZpbGUoZmlsZU5hbWUpOw0KRmlsZVdyaXRl
ciBmdzsNCkJ1ZmZlcmVkV3JpdGVyIGJ3Ow0KDQp0cnl7DQoJaWYoIWYuZXhpc3RzKCkpDQoJew0K
CQkgICBmLmNyZWF0ZU5ld0ZpbGUoKTsNCgl9CQkNCglmdyA9IG5ldyBGaWxlV3JpdGVyKGYuZ2V0
QWJzb2x1dGVQYXRoKCksdHJ1ZSk7DQoJYncgPSBuZXcgQnVmZmVyZWRXcml0ZXIoZncpOw0KCWJ3
LndyaXRlKGlucHV0U3RyKTsNCglidy5jbG9zZSgpOw0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5l
Q3Vyc29yXzEsICJ3cml0ZVN0YXR1cyIsICJTdWNjZXNzIiApOw0KfQ0KY2F0Y2goRXhjZXB0aW9u
IGV4KQ0Kew0KCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ3cml0ZVN0YXR1cyIs
ICJGYWlsZWQiICk7DQp9DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCgk=</value>
</Values>
