<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getDocumentNames</value>
  <value name="encodeutf8">true</value>
  <value name="body">QXJyYXlMaXN0PFN0cmluZz4gYSA9bmV3IEFycmF5TGlzdDxTdHJpbmc+KCk7DQpTdHJpbmdbXQlw
YXRoPSBudWxsOw0KLy8gcGlwZWxpbmUNCiBJRGF0YU1hcCBwaXBlbGluZU1hcCA9IG5ldyBJRGF0
YU1hcChwaXBlbGluZSk7DQogSURhdGEgcGF0aHMgPSBwaXBlbGluZU1hcC5nZXRBc0lEYXRhKCJw
YXRocyIpOw0KaWYgKG51bGw9PXBhdGhzKXt9IGVsc2V7DQogSURhdGFDdXJzb3IgcGljPXBhdGhz
LmdldEN1cnNvcigpOw0KDQp3aGlsZShwaWMuaGFzTW9yZURhdGEoKSl7DQpwaWMubmV4dCgpOw0K
CWEuYWRkKHBpYy5nZXRLZXkoKSk7DQp9DQp9DQppZihhLmlzRW1wdHkoKSl7fSBlbHNlew0KcGF0
aD1hLnN0cmVhbSgpLnRvQXJyYXkoU3RyaW5nW106Om5ldyk7fQ0KcGlwZWxpbmVNYXAucHV0KCJw
YXRoIiwgcGF0aCk7</value>
</Values>
